### ISSUE TITLE
Adjust Default Port to not Conflict with Xdebug Default Port

### ISSUE THREAD

**Issue by cybtachyon** [mechevarria/patternfly-seed#1]
As per https://xdebug.org/docs/all_settings#remote_port , xdebug sits on 9000 as a default.

This means if you're XDebugging a PHP Rest server for your angular patternfly app, you'll need to swap one of the ports - and go figure neither give the most helpful of error messages when running into the issues.

I understand that `grunt serve` has been using 9000 since 2014, but Xdebug has been using it since 2002.

To avoid bikeshedding, I would like to suggest we either go with 9001 or decide to ignore the issue and make it the burden of the developer to be aware of the possible port conflict.

Parallel issue for grunt serve: https://github.com/lud2k/grunt-serve/issues/13

**Comment by mechevarria** [comment]
Its a dev port, so I put it to 9001
